version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: my-sql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: sa
      MYSQL_DATABASE: deneme1
      MYSQL_USER: root
      MYSQL_PASSWORD: sa
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - writers-club-network

volumes:
  mysql_data:

networks:
  writers-club-network:
    driver: bridge
